---
# tasks file for deploy_gds

- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: path4build

# Git clone
- name: Clone Get Datetime Server project
  git:
    repo: "https://github.com/jim1406g/get_datetime_server.git"
    dest: "{{ path4build.path }}"

# Docker build
- name: Build docker image
  docker_image:
    name: "get_datetime_server"
    build:
      path: "{{ path4build.path }}"
      pull: no
    force_source: yes
    source: build
    state: present

- name: Delete temporary build directory
  file:
    path: "{{ path4build.path }}"
    state: absent

- include: install_service.yml
